config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :items

  root 'categories#index'
  #post 'items#new'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @sort_items = @category.items.to_a.sort! { |x,y| y.created_at<=>x.created_at }
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :descripton)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def new
    @item = Item.new
    @categories = Category.all
  end

  def show
  end

  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item.category, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
    item = @item
    @item.destroy
    respond_to do |format|
      format.html { redirect_to item.category, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:category_id, :name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descripton %><br>
    <%= f.text_field :descripton %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

  <div>
    <h1>Categories</h1>
    <%= link_to 'New Category', new_category_path %>
  </div>


  <% @categories.each do |category| %>
    <div id="categories">
      <h2><%= link_to category.name, category%></h2>
      <%= category.descripton %>
    </div>
  <% end %>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h1> <%= @category.name %> </h1>
  <%= @category.descripton %>
</div>
<br>
<table>
  <tr id="main">
    <th id="main">Item</th>
    <th id="main">Price</th>
    <th id="main">Date</th>
  </tr>
  <% sum = 0 ; quantity = 0%>
  <% @sort_items.each do |item| %>
    <% sum += item.price ; quantity += 1%>
    </tr>
      <th> <%= link_to item.name, item%> </th>
      <th> <%= item.price %> </th>
      <th> <%= item.created_at.strftime("%d/%m/%Y") %> </th>
    </tr>
  <% end %>
</table>

<h2> Total Cost = R$ <%= sum %> </h2>
<h2>Average Cost per item: <%= (sum/quantity).round(1) %> </h2>
<br><br><br>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'New Item', new_item_path %> |
<%= link_to 'Back', categories_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, value: 0, step: 'any' %>
  </div>
  <div class="field">
    <%= f.label :Category %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form'%>

<%= link_to 'Back', root_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @item.name %></h1>
<br><br>

<strong>Price: </strong>
<%= @item.price %>

<br><br>
<strong>Category: </strong>
<%= @item.category.name %>

<br><br>
<strong>Date:</strong>
<%= @item.created_at.strftime("%d/%m/%Y") %>
<strong> at: </strong>
<%= @item.created_at.strftime("%H:%M:%S") %>

<br><br>
<%= link_to 'Back', @item.category %> |
<%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CostManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Patrick+Hand' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body id="main">

<%= yield %>

</body>
</html>